<<<<<<< HEAD
"""
An enum class containing all the possible environments for the SDK
"""

=======
# This file was generated by liblab | https://liblab.com/

"""
An enum class containing all the possible environments for the SDK
"""
>>>>>>> 95da91c (initial commit)
from enum import Enum


class Environment(Enum):
    """The environments available for the SDK"""

    DEFAULT = "https://api.getpostman.com"
<<<<<<< HEAD
    US = "https://api.getpostman.com"
    EU = "https://api.eu.postman.com"
=======
>>>>>>> 95da91c (initial commit)
