# This file was generated by liblab | https://liblab.com/

from enum import Enum


class Accept(Enum):
    """An enumeration representing different categories.

    :cvar APPLICATIONVNDAPIV10JSON: "application/vnd.api.v10+json"
    :vartype APPLICATIONVNDAPIV10JSON: str
    """

    APPLICATIONVNDAPIV10JSON = "application/vnd.api.v10+json"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Accept._member_map_.values()))
