# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class CreateCollectionForkRequest(BaseModel):
    """CreateCollectionForkRequest

    :param label: The fork's label.
    :type label: str
    """

    def __init__(self, label: str):
        """CreateCollectionForkRequest

        :param label: The fork's label.
        :type label: str
        """
        self.label = label
