# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetWorkspacesInclude(Enum):
    """An enumeration representing different categories.

    :cvar MOCKSDEACTIVATED: "mocks:deactivated"
    :vartype MOCKSDEACTIVATED: str
    """

    MOCKSDEACTIVATED = "mocks:deactivated"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, GetWorkspacesInclude._member_map_.values()))
