# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class GetCollection(BaseModel):
    """GetCollection

    :param collection: For a complete list of this endpoint's possible values, use the [collection.json schema file](https://schema.postman.com/json/collection/v2.1.0/collection.json)., defaults to None
    :type collection: dict, optional
    """

    def __init__(self, collection: dict = None):
        """GetCollection

        :param collection: For a complete list of this endpoint's possible values, use the [collection.json schema file](https://schema.postman.com/json/collection/v2.1.0/collection.json)., defaults to None
        :type collection: dict, optional
        """
        if collection is not None:
            self.collection = collection
