# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"id_": "id"})
class MergeCollectionForkCollection(BaseModel):
    """MergeCollectionForkCollection

    :param id_: The source collection's ID., defaults to None
    :type id_: str, optional
    :param uid: The source collection's unique ID., defaults to None
    :type uid: str, optional
    """

    def __init__(self, id_: str = None, uid: str = None):
        """MergeCollectionForkCollection

        :param id_: The source collection's ID., defaults to None
        :type id_: str, optional
        :param uid: The source collection's unique ID., defaults to None
        :type uid: str, optional
        """
        if id_ is not None:
            self.id_ = id_
        if uid is not None:
            self.uid = uid


@JsonMap({})
class MergeCollectionForkOkResponse(BaseModel):
    """MergeCollectionForkOkResponse

    :param collection: collection, defaults to None
    :type collection: MergeCollectionForkCollection, optional
    """

    def __init__(self, collection: MergeCollectionForkCollection = None):
        """MergeCollectionForkOkResponse

        :param collection: collection, defaults to None
        :type collection: MergeCollectionForkCollection, optional
        """
        if collection is not None:
            self.collection = self._define_object(
                collection, MergeCollectionForkCollection
            )
