# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class TransferCollectionItems200Error(BaseModel):
    """TransferCollectionItems200Error

    :param ids: A list of the transferred collection request, response, or folder UIDs., defaults to None
    :type ids: List[str], optional
    """

    def __init__(self, ids: List[str] = None):
        """TransferCollectionItems200Error

        :param ids: A list of the transferred collection request, response, or folder UIDs., defaults to None
        :type ids: List[str], optional
        """
        if ids is not None:
            self.ids = ids
