# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"parent_folder_id": "parentFolderId"})
class UpdatePanApiApi(BaseModel):
    """UpdatePanApiApi

    :param parent_folder_id: The API's new parent folder ID., defaults to None
    :type parent_folder_id: int, optional
    """

    def __init__(self, parent_folder_id: int = None):
        """UpdatePanApiApi

        :param parent_folder_id: The API's new parent folder ID., defaults to None
        :type parent_folder_id: int, optional
        """
        if parent_folder_id is not None:
            self.parent_folder_id = parent_folder_id


@JsonMap({})
class UpdatePanApi(BaseModel):
    """UpdatePanApi

    :param api: api, defaults to None
    :type api: UpdatePanApiApi, optional
    """

    def __init__(self, api: UpdatePanApiApi = None):
        """UpdatePanApi

        :param api: api, defaults to None
        :type api: UpdatePanApiApi, optional
        """
        if api is not None:
            self.api = self._define_object(api, UpdatePanApiApi)
